### ISSUE TITLE
Move functionality into class methods

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/azure-img-utils#33]
Where the class methods call utility functions with similar names the code can move to the class method and the utility can be dropped. For example `AzureImage.create_compute_image` calls `create_image` to do the actual image creation. This can be consolidated in the class. This solves the name clashing issue and leaves utils modules for functions that don't fit nicely in the class or to prevent duplication.

**Comment by apozsuse** [comment]
While we get the ec2imgutils PRs merged I'll have a look at this... 👀
